#!/usr/bin/ruby
# uses the system ruby so we can access ruby-cocoa

require "osx/cocoa"

class AppDelegate < OSX::NSObject
  def application_openFiles(application, files)
    launch_mplayer(files.to_ruby.reject {|f| f == __FILE__})
    true
  end

  private
  def mplayer_binary
    File.join(File.dirname(__FILE__), "mplayer2bin")
  end

  def launch_mplayer(files)
    if files.size > 0 then
      files_string = files.map{|file| %Q{"#{file}"} }.join(" ")
      # calls unix exec to replace the running code with mplayer
      exec(%Q{"#{mplayer_binary}" #{files_string}})
    end
  end
end

# Instantiate the shared App
app = OSX::NSApplication.sharedApplication

app.setDelegate AppDelegate.alloc.init
app.run
